use super::Bundle;
use serde_json::json;
pub(super) fn all() -> Vec<Bundle> {
    [
        json!({"format":"shadowcode-plugin-v1","name":"python-expert","version":"2.0.0","description":"Python build and test workflows, Ruff formatting and commit lint checks. Requires the project's own Python and Ruff tools.",
            "skills":{"python-build":{"description":"Inspect, test and package a Python project","content":"Inspect pyproject.toml, project instructions and the existing environment first. Work on $ARGUMENTS. Use the project's selected interpreter and dependency manager; do not replace an existing environment. Run the configured lint and test commands, then build the package if requested. Report actual commands, failures and artifacts. Dependency installation needs the ordinary command/network permissions."}},
            "commands":{"ruff-format":{"description":"Review and apply the project's Ruff formatting","content":"Inspect the Ruff configuration and current diff. Format only the requested files ($ARGUMENTS), or explain the project-wide scope before running Ruff. Run the project's formatter through the terminal approval flow and review the resulting diff."},"pytest-watch":{"description":"Start a managed Python test watcher when available","content":"Inspect the project's test and watch configuration for $ARGUMENTS. If a watcher is already installed, propose its exact command and start it with background_start after approval. Otherwise run the tests once and explain the missing watcher. Do not install dependencies automatically. Report the managed process ID and how to stop it."}},
            "hooks":[{"name":"ruff-format","description":"After a Python edit, format the whole project with its installed Ruff. Enable only after reviewing this project-wide scope.","events":["after_edit"],"path_suffix":".py","command":"ruff format .","timeout_sec":30},{"name":"ruff-check","description":"Require Ruff lint checks to pass before committing.","events":["before_commit"],"command":"ruff check .","timeout_sec":60}]}),
        json!({"format":"shadowcode-plugin-v1","name":"linux-expert","version":"2.0.0","description":"Linux packaging, AppImage, Debian package and service review workflows using the project's build tools.",
            "skills":{"appimage":{"description":"Build and verify a project's AppImage","content":"Inspect the project's existing packaging instructions and scripts. For $ARGUMENTS, build its release executable, stage the documented AppDir, check desktop/icon/version metadata and bundled license notices, and use the project's pinned packaging tool. Inspect the resulting image, smoke-test with an isolated profile and generate a checksum. Do not publish or replace installed applications unless requested."},"apt-package":{"description":"Build and inspect a Debian package","content":"Inspect the project's existing Debian packaging and build instructions for $ARGUMENTS. Build the package using its configured tools. Inspect control metadata, file paths, permissions, dependencies and license notices; run available package lint checks. Report the artifact and checksum. Installation and system changes require explicit user intent and configured permissions."},"service-review":{"description":"Review a systemd service without changing the system","mode":"review","content":"Review $ARGUMENTS and associated systemd unit files. Inspect executable paths, users, environment/credential references, restart behavior, dependencies and shutdown handling. Explain concrete failures and proposed changes. Do not enable, start, stop or install services during this review."}},
            "commands":{"apt-info":{"description":"Inspect Debian package metadata","mode":"review","content":"Inspect available package metadata for $ARGUMENTS using project files and read-only package queries. Explain dependencies and installed versus available versions using actual output. Do not update package lists or install software."},"appimage-build":{"description":"Follow the project's AppImage build workflow","content":"Use the installed linux-expert--appimage skill file as guidance for $ARGUMENTS. Inspect the actual project scripts before building and verify the resulting package. Do not publish without explicit user intent."}}}),
        json!({"format":"shadowcode-plugin-v1","name":"ios","version":"1.0.0","description":"Xcode project inspection and build guidance. Building requires macOS and project-provided Xcode tooling.","skills":{"xcode-build":{"description":"Inspect and build an Xcode project on a supported host","content":"Inspect the platform, workspace/project, schemes and signing configuration for $ARGUMENTS. On macOS with Xcode installed, use the project's documented xcodebuild command and report its real result. On other platforms, review sources and explain which build steps require a macOS host. Do not change signing identities or upload artifacts without explicit user intent."}}}),
    ].into_iter().map(|value| Bundle::parse(value).expect("valid built-in plugin")).collect()
}
